### ISSUE TITLE
"SyntaxError: invalid character in identifier" on files with the UTF-8-BOM

### ISSUE THREAD

**Issue by karyon** [PyCQA/mccabe#39]
on a file that has the UTF-8-BOM (see this [stackoverflow post](http://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom)), mccabe throws something like this:

```
vagrant@localhost:/vagrant$ python -m mccabe --min 5 evap/grades/templatetags/grades_templatetags.py
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/mccabe.py", line 310, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/mccabe.py", line 292, in main
    tree = compile(code, args[0], "exec", ast.PyCF_ONLY_AST)
  File "evap/grades/templatetags/grades_templatetags.py", line 1
    ﻿from django.template import Library
        ^
SyntaxError: invalid character in identifier
```
before this error, i didn't even know this BOM thing existed and i needed quite a while to figure it out. while i generally don't think such archaic stuff needs to be supported, i think mccabe could handle this more gracefully, especially since it is allowed per the standard and all other tools don't seem to be bothered by those bytes.

example file that has the BOM: https://raw.githubusercontent.com/fsr-itse/EvaP/803ac9825aac1024137220bed631e4302d580d18/evap/grades/templatetags/grades_templatetags.py

**Comment by sigmavirus24** [comment]
Thanks for this excellent bug report @karyon. I think I know how to work around this and why I haven't seen it before.

**Comment by carlio** [comment]
fwiw, this is how prospector handles BOMs: https://github.com/landscapeio/prospector/blob/master/prospector/encoding.py#L15 - added that a while ago thanks to a PR (that I now can't find)
